apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-project-deployment
spec:
  selector:
    matchLabels:
      app: ci-cd-project-deployment
  replicas: {{ .Values.deployment.replicaCount }}
  template:
    metadata:
      labels:
        app: ci-cd-project-deployment
    spec:
      containers:
      - name: ci-cd-project-deployment
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        args:
          - DB_HOST
          - 127.0.0.1
        ports:
        - containerPort: {{ .Values.container.port }}