apiVersion: v1
kind: Service
metadata:
  name: ci-cd-project-service
spec:
  selector:
    app: ci-cd-project-deployment
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: {{ .Values.container.port }}
  type: {{ .Values.service.type }}